version: '3.1'

services:
  master:
    image: redis:7.0
    container_name: redis-1
    command: redis-server --port 6380
    network_mode: "host"
    volumes:
      - ./data/redis1:/data
  slave1:
    image: redis:7.0
    container_name: redis-2
    command: redis-server --port 6381 --replicaof 10.100.97.80 6380
    network_mode: "host"
    volumes:
      - ./data/redis2:/data
    depends_on: ["master"]
  slave2:
    image: redis:7.0
    container_name: redis-3
    command: redis-server --port 6382 --replicaof 10.100.97.80 6380
    network_mode: "host"
    volumes:
      - ./data/redis3:/data
    depends_on: ["master"]
  sentinel1:
    image: redis:7.0
    container_name: redis-sentinel-1
    command: redis-sentinel /data/sentinel.conf
    network_mode: "host"
    volumes:
      - ./config/sentinel1:/data
    depends_on: ["master", "slave1", "slave2"]
  sentinel2:
    image: redis:7.0
    container_name: redis-sentinel-2
    command: redis-sentinel /data/sentinel.conf
    network_mode: "host"
    volumes:
      - ./config/sentinel2:/data
    depends_on: ["master", "slave1", "slave2"]
  sentinel3:
    image: redis:7.0
    container_name: redis-sentinel-3
    command: redis-sentinel /data/sentinel.conf
    network_mode: "host"
    volumes:
      - ./config/sentinel3:/data
    depends_on: ["master", "slave1", "slave2"]