version: '3.1'

services:
  redis1:
    image: redis:7.0
    container_name: cluster-redis-1
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file redis-node1.conf
    network_mode: host
    volumes:
      - ./data/redis1:/data
    restart: always
  redis2:
    image: redis:7.0
    container_name: cluster-redis-2
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file redis-node2.conf
    network_mode: host
    volumes:
      - ./data/redis2:/data
    restart: always
  redis3:
    image: redis:7.0
    container_name: cluster-redis-3
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file redis-node3.conf
    network_mode: host
    volumes:
      - ./data/redis3:/data
    restart: always
  redis4:
    image: redis:7.0
    container_name: cluster-redis-4
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file redis-node4.conf
    network_mode: host
    volumes:
      - ./data/redis4:/data
    restart: always
  redis5:
    image: redis:7.0
    container_name: cluster-redis-5
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file redis-node5.conf
    network_mode: host
    volumes:
      - ./data/redis5:/data
    restart: always
  redis6:
    image: redis:7.0
    container_name: cluster-redis-6
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file redis-node6.conf
    network_mode: host
    volumes:
      - ./data/redis6:/data
    restart: always